### ISSUE TITLE
No app-localizations.g.dart is generated

### ISSUE THREAD

**Issue by vorlovsky** [kwado-tech/l10n_mapper#14]
After several attempts I'm still unable to make _app-localizations.g.dart_ to be generated. 
I've provided a clear test project with only _flutter_localization_, _intl_, _l10n_mapper_annotation_ and _l10n_mapper_generator_ added (basic `AppLocalization `class is generated, linked and works fine there):
[test_drive.zip](https://github.com/kwado-tech/l10n_mapper/files/14431600/test_drive.zip)

Notes:
I've followed all the steps from your README, _Mapper_ section.

All the _l10n_mapper_ scripts run without any issues - and also without any result besides creation of _app-localizations.dart.bak_.

I was able to fix _scripts/annotate_localization.dart_ by setting up a correct search string for annotations (line 39): 
`String searchParameter = 'abstract class AppLocalizations {\n';`
replaced with
`String searchParameter = 'abstract class AppLocalizations {';`
This one enabled annotations to be actually applied upon `dart pub run l10n_mapper_generator --gen-mapper`.

Unfortunately, I'm not that experienced to figure out what's wrong with `L10nMapperGenerator.generateForAnnotatedElement` being called upon `flutter pub run build_runner build`. This command's output shows no errors, but _app-localizations.g.dart_ does not appear.

Can you, please, check it and fix, or at least advice me how could I debug calls to `L10nMapperGenerator.generateForAnnotatedElement` during build? Do you need any more information from my side for it?

**Comment by kwado-tech** [comment]
Hi @vorlovsky I have been terribly busy and unavailable for some time but will take a look at your code within the week to understand the issues and resolve the resulting bug in the package

**Comment by kwado-tech** [comment]
Hey @vorlovsky finally found sometime to look into this and noticed the issues you indicated.

The issue with annotation was rightly pointed out and removing the line break worked as expected. However the generator failed because your project was setup to generate `synthetic` localization package in  `.dart_tool` and changing this worked as expected as well as l10n-mapper does not support synthetic localization package.

Made a few changes to your setup
- l10n.yaml
- l10n_mapper.json
- renamed `lib/l10n` to `lib/translations` which makes more sense in the given context
- pubspec.yaml - removed `generate: true`

PS. Will publish fixes in a couple of hours

[test_drive.zip](https://github.com/kwado-tech/l10n_mapper/files/14622225/test_drive.zip)
