### ISSUE TITLE
Optimisation opportunity

### ISSUE THREAD

**Issue by talamaska** [kwado-tech/l10n_mapper#18]
Just a speculation here
I haven't really measured anything or performed any performance tests.
I was looking at the AppLocalizationMapper.
The first thing that comes into focus is that it is instantiated every time l10nParser is called.
That wouldn't be an issue normally, but the map is composed on runtime and potentially can have thousands of records.
For every key you search for the AppLocalization with dependOnInheritedWidgetOfExactType up in the tree. The translation could potentially be called very deep.
So I was wondering why not cache it, like so:
```dart
class AppLocalizationsMapper {
  const AppLocalizationsMapper();
  Map<String, dynamic> toLocalizationMap(BuildContext context) {
    final localization = AppLocalizations.of(context);
    return {
      'localeName': localization!.localeName,
      'signIn': localization!.signIn,
      'signOut': localization!.signOut,
      'signUp': localization!.signUp,
    };
  }
}
```

Feels like a low hanging fruit that cannot cause harm.
further down the road I would imagine being able to cache maps for different locales.
Like so:
```dart
final Map<String, AppLocalizationsMapper> cachedMaps = {};

extension AppLocalizationsExtension on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this)!;
  Locale get locale => Localizations.localeOf(this);
  String l10nParser(String translationKey, {List<Object>? arguments}) {
    var mapper;
    if (!cachedMaps.containsKey(locale.languageCode)) {
      mapper = AppLocalizationsMapper();
      cachedMaps[locale.languageCode] = mapper;
    } else {
      mapper = cachedMaps[locale.languageCode];
    }

    final object = mapper.toLocalizationMap(this)[translationKey];
    if (object == null) return 'Cannot find translation-key!';
    if (object is String) return object;
    assert(arguments != null, 'Arguments should not be null!');
    assert(arguments!.isNotEmpty, 'Arguments should not be empty!');
    return Function.apply(object, arguments);
  }
}

```

**Comment by kwado-tech** [comment]
Hey @talamaska, interesting perception. 

Given your view, the first example is cleaner (resolves replication of `AppLocalizations.of(context)` throughout the map object) but offers no benefit in relation to optimisation. This is because `l10nParser` method is always called and re-instantiates `AppLocalizationsMapper` which is a cheap operation (provided the usage in context - at a given time does not exceed language constraints) and also reading map values from `toLocalizationMap` method per `l10nParser` extension method call is `O(1)` time complexity (worst case scenario) and also lazy as `AppLocalizations.of(context)` will only be evaluated when call and not when the map was created.

Secondly, the intention of the l10n-mapper package is not to manage localisation/translation context as your second proposition expresses (with caching strategy) but enable access to translations/localisation objects already managed by flutter l10n setup.

Given these, more optimization is absolutely welcomed even if this is pretty fast as it has similar read time as a `AppLocalizations.of(context).someTraslationKey` direct call.

I'll close this. Feel free to reopen if you have some doubts.
